routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'as' => 'main',
    'uses' => 'MainPageController@index'
]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::delete('/comments/{id}', [
    'as' => 'comments.destroy',
    'uses' => 'CommentController@destroy',
    'middleware' => 'admin'
]);

Route::resource('comments', 'CommentController')
    ->only(['index', 'store']);

Route::post('/ban-user/{id}', [
    'as' => 'users.ban',
    'uses'=> 'UserController@banUser',
    'middleware' => 'admin'
]);

Route::post('/unban-user/{id}', [
    'as' => 'users.unban',
    'uses'=> 'UserController@unbanUser',
    'middleware' => 'admin'
]);

Route::get('users/profile', [
    'as' => 'users.profile',
    'uses' => 'UserController@profile',
    'middleware' => 'auth'
]);

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [
        'user_id',
        'body'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_banned'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isAdmin()
    {
        return auth()->check() && auth()->id() == 1;
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Http\Requests\CommentRequest;
use App\User;

class CommentController extends Controller
{
    public function store(CommentRequest $r)
    {
        $user = auth()->check() ? auth()->user() : User::whereEmail($r->email)->first();

        if (!$user) {
            $user = factory(User::class)->create([
                'email' => $r->email
            ]);
        }

        Comment::create([
            'user_id' => $user->id,
            'body' => $r->body
        ]);

        session()->flash('comment_status', 'created');
        return redirect()->back();
    }

    public function destroy($id)
    {
        Comment::destroy($id);

        return redirect()->back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MainPageController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Illuminate\Http\Request;

class MainPageController extends Controller
{
    public function index()
    {
        $comments = Comment::with('user')
            ->orderBy('id', 'desc')
            ->paginate(5);

        $isAdmin = auth()->check() ? auth()->user()->isAdmin() : null;

        return view('main.index', compact('comments', 'isAdmin'));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function banUser($id){
        $user = User::findOrFail($id);
        $user->is_banned = true;
        $user->save();

        return redirect()->back();
    }

    public function unbanUser($id){
        $user = User::findOrFail($id);
        $user->is_banned = false;
        $user->save();

        return redirect()->back();
    }

    public function profile()
    {
        $comments = Comment::whereUserId(auth()->id())
            ->orderBy('id', 'DESC')
            ->paginate(15);

        return view('user.profile', compact('comments'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('users.profile') }}">@lang('comment.profile')</a>

                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            @yield('content')
        </div>
    </div>
</body>
</html>

resources/views/main/index.blade.php
@extends('layouts.app')

@section('content')
    @if(!auth()->check() || auth()->check() && !auth()->user()->is_banned)
        <!-- Form -->
        <div class="pa-md">
            @if(session()->get('comment_status') == 'created')
                <div class="alert alert-primary" role="alert">
                    @lang('comment.comment_was_saved')
                </div>
            @endif

            <form action="{{ route('comments.store') }}" method="POST">
                @csrf
                @guest()
                    <div class="form-group">
                        <label for="exampleInputEmail1">@lang('comment.email')</label>
                        <input type="email" name="email" value="{{ old('email') }}"
                               class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                               placeholder="@lang('comment.enter_email')">
                        @error('email')
                        <small class="form-text text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                @endguest

                <div class="form-group">
                    <label for="exampleFormControlTextarea1">@lang('comment.comment')</label>
                    <textarea class="form-control{{ $errors->has('body') ? ' is-invalid' : '' }}" name="body" rows="3"
                              placeholder="@lang('comment.enter_comment')"></textarea>
                    @error('body')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <button class="btn btn-primary" type="submit">
                    @lang('comment.leave_comment')
                </button>
            </form>
        </div>
    @endif

    <!-- Comments -->
    @foreach($comments as $comment)
        <div class="pa-md">
            <p>{{ $comment->body }}</p>

            <!-- Ban user -->
            @if($isAdmin && !$comment->user->is_banned)
                <form class="float-right" action="{{ route('users.ban', $comment->user->id) }}" method="POST">
                    @csrf
                    <button class="btn btn-danger">@lang('comment.ban_user')</button>
                </form>
            @endif

        <!-- Unban user -->
            @if($isAdmin && $comment->user->is_banned)
                <form class="float-right" action="{{ route('users.unban', $comment->user->id) }}" method="POST">
                    @csrf
                    <button class="btn btn-primary">@lang('comment.unban_user')</button>
                </form>
            @endif
            <div class="float-right pa-md">{{ $comment->user->email }}</div>

            <hr class="clear-both"/>

            @if($isAdmin)
                <form action="{{ route('comments.destroy', $comment->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger">@lang('comment.delete_comment')</button>
                </form>
            @endif
        </div>
    @endforeach

    <!-- Pagination -->
    <div class="pa-md">
        {{ $comments->links() }}
    </div>
@endsection

resources/views/user/profile.blade.php
@extends('layouts.app')

@section('content')
    @foreach($comments as $comment)
        <div class="pa-md">
            <p>{{ $comment->body }}</p>
            <hr class="pt-md"/>
        </div>

        {{ $comments->links() }}
    @endforeach
@endsection